package routers

import (
	"github.com/gin-gonic/gin"
	//_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
	"src/controllers/api"
	_ "src/docs" /* doc files */
)

func InitRouter() *gin.Engine {
	r := gin.Default()

	// Simple group: v1
	v1 := r.Group("api/v1")
	{
		v1.POST("/users/signin", api.SignIn)
		v1.POST("/users/register", api.Register)
		v1.GET("/users/:id", api.GetUser)
		v1.PUT("/users/:id", api.PutUser)
		v1.DELETE("/users/:id", api.DelUser)
		v1.GET("/users", api.GetUsers)
	}

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{"message": "pong"})
	})

	return r
}
