package main

import (
	"flag"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"src/db"
	//_ "src/docs" // docs is generated by Swag CLI, you have to import it.
	"src/log"
	"src/routers"
	"src/utils/config"
)

var configFile = flag.String("config", "../config/config.yaml", "配置文件路径")

func init() {
	flag.Parse()

	config.InitConfig(*configFile) // 初始化配置
	log.InitLogrus()               // 初始化日志
	db.InitDB()                    // 初始化数据库
}

// @title demo-gin-mpvue
// @version 0.0.1
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url
// @contact.email chenganggo@gmail.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1/
func main() {
	r := routers.InitRouter() //初始化路由

	// use ginSwagger middleware to
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	r.Run(":8080")
}
