package route

import (
	"github.com/gin-gonic/gin"
	"src/util/config"

	//_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
	"src/controller/api"
	_ "src/docs" /* doc files */
)

func InitRouter() *gin.Engine {
	gin.SetMode(config.Conf.AppMode)

	engine := gin.New()

	// Simple group: v1
	v1 := engine.Group("api/v1")
	{
		v1.POST("/users/signin", api.SignIn)
		v1.POST("/users/register", api.Register)
		v1.GET("/users/:id", api.GetUser)
		v1.PUT("/users/:id", api.PutUser)
		v1.DELETE("/users/:id", api.DelUser)
		v1.GET("/users", api.GetUsers)
	}

	engine.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{"message": "pong"})
	})

	return engine
}
